# Generated by Django 3.1.6 on 2021-10-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='车型名称')),
            ],
            options={
                'verbose_name': '车型名称',
                'verbose_name_plural': '车型管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('port', models.IntegerField(verbose_name='端口号')),
            ],
            options={
                'verbose_name': '串口配置',
                'verbose_name_plural': '串口配置',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, null=True)),
                ('belong_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户名',
                'verbose_name_plural': '用户身份管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='故障名')),
                ('card', models.IntegerField(blank=True, null=True, verbose_name='板卡号')),
                ('address', models.IntegerField(blank=True, null=True, verbose_name='故障地址')),
                ('status', models.IntegerField(blank=True, choices=[(0, '正常'), (1, '故障'), (2, '断路')], null=True, verbose_name='当前状态')),
                ('belong_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_class', to='data.classification', verbose_name='车型')),
            ],
            options={
                'verbose_name': '故障名称',
                'verbose_name_plural': '故障设置',
                'ordering': ['id'],
            },
        ),
    ]
