# Generated by Django 3.1.6 on 2021-10-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=50, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级名称',
                'verbose_name_plural': '班级管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='院系名称')),
            ],
            options={
                'verbose_name': '院系名称',
                'verbose_name_plural': '院系管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('tid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='教工号')),
                ('password', models.CharField(default='qichezhinengyitihua', max_length=50, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('belong_De', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_Dep', to='usermanage.department', verbose_name='所属院系')),
                ('belong_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '教师名称',
                'verbose_name_plural': '教师管理',
                'ordering': ['tid'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='学号')),
                ('password', models.CharField(default='qichezhinengyitihua', max_length=50, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('belong_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_Cl', to='usermanage.classes', verbose_name='所在班级')),
            ],
            options={
                'verbose_name': '学生名字',
                'verbose_name_plural': '学生管理',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='belong_De',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_De', to='usermanage.department', verbose_name='所属院系'),
        ),
    ]
