# Generated by Django 3.1.6 on 2021-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='en',
            field=models.BooleanField(default=True),
        ),
    ]
