# Generated by Django 3.1.6 on 2021-10-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_auto_20211020_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': '教师名称', 'verbose_name_plural': '教师管理'},
        ),
        migrations.AlterField(
            model_name='teachers',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='启用'),
        ),
    ]
