# Generated by Django 3.1.6 on 2021-10-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50, verbose_name='列名称')),
            ],
            options={
                'verbose_name': '列',
                'verbose_name_plural': '列',
            },
        ),
        migrations.CreateModel(
            name='contestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='竞赛名称')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('disorder', models.BooleanField(default=False, verbose_name='模块乱序')),
                ('images', models.ImageField(blank=True, null=True, upload_to='contestList/', verbose_name='展示图')),
                ('type', models.IntegerField(choices=[(0, '实训'), (1, '竞赛')], default=0, verbose_name='类型')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作业项目')),
                ('serial', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('description', models.CharField(default='无', max_length=50, verbose_name='简介')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
            ],
            options={
                'verbose_name': '作业项目',
                'verbose_name_plural': '作业项目',
            },
        ),
        migrations.CreateModel(
            name='job_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作业小项')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='配分')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
            ],
            options={
                'verbose_name': '作业小项',
                'verbose_name_plural': '作业小项',
            },
        ),
        migrations.CreateModel(
            name='Modula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('belong_contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目')),
                ('belong_modula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.modula', verbose_name='模块')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50, verbose_name='表格名')),
                ('column_header', models.CharField(max_length=10, verbose_name='列表头')),
                ('row_header', models.CharField(max_length=10, verbose_name='行表头')),
                ('belong_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
            ],
            options={
                'verbose_name': '记录表',
                'verbose_name_plural': '记录表',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_name', models.CharField(max_length=50, verbose_name='行名称')),
                ('type', models.CharField(choices=[('float', '数值'), ('select-1', '判断')], default='数值', max_length=10, verbose_name='类型')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.record', verbose_name='表格')),
            ],
            options={
                'verbose_name': '行',
                'verbose_name_plural': '行',
            },
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工位号')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
            },
        ),
        migrations.CreateModel(
            name='TableRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50, verbose_name='答题')),
                ('judge_answer', models.IntegerField(blank=True, choices=[(1, '正常'), (2, '维修'), (3, '更换'), (4, '调整')], null=True, verbose_name='判断正确值')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('belong_contestList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.column', verbose_name='列')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.row', verbose_name='行')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.record', verbose_name='表格')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TableJobScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='分数')),
                ('submit', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('belong_contestList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '表格成绩',
                'verbose_name_plural': '表格成绩',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='步骤')),
                ('tools', models.CharField(blank=True, max_length=100, null=True, verbose_name='工具')),
                ('images', models.ImageField(blank=True, null=True, upload_to='contest/', verbose_name='展示图')),
                ('programme', models.CharField(blank=True, max_length=100, null=True, verbose_name='方案')),
                ('attention', models.CharField(blank=True, max_length=100, null=True, verbose_name='注意事项')),
                ('belong_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '步骤',
                'verbose_name_plural': '步骤',
            },
        ),
        migrations.CreateModel(
            name='Results_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='分数')),
                ('submit', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('type', models.CharField(choices=[('评分', '评分'), ('理论', '理论')], default='理论', max_length=10, verbose_name='类型')),
                ('belong_contestList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '学生成绩',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multiple_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('answer', models.CharField(max_length=10, verbose_name='答题')),
                ('belong_contestList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.multiple_choice', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '多选题记录',
                'verbose_name_plural': '多选题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multiple_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.multiple_choice', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '多选题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('answer', models.CharField(max_length=10, verbose_name='答题')),
                ('belong_contestList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.judge', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '判断题记录',
                'verbose_name_plural': '判断题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.judge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '判断题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='jobTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, default='0', max_digits=5, verbose_name='总分')),
                ('images', models.ImageField(blank=True, null=True, upload_to='jobTotal/', verbose_name='裁判签名')),
                ('submit', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('alter_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('belong_contestList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.station', verbose_name='工位号')),
                ('studen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='教师')),
            ],
            options={
                'verbose_name': '总分',
                'verbose_name_plural': '总分',
            },
        ),
        migrations.CreateModel(
            name='jobScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='配分')),
                ('belong_contestList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job_item', verbose_name='作业小项目')),
                ('belong_st', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.station', verbose_name='工位号')),
                ('studen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='教师')),
            ],
            options={
                'verbose_name': '配分',
                'verbose_name_plural': '配分',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='正确值')),
                ('judge_answer', models.IntegerField(blank=True, choices=[(1, '正常'), (2, '维修'), (3, '更换'), (4, '调整')], null=True, verbose_name='判断正确值')),
                ('error', models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=5, null=True, verbose_name='误差')),
                ('score', models.DecimalField(blank=True, decimal_places=2, default='2', max_digits=5, null=True, verbose_name='分值')),
                ('type', models.CharField(choices=[('float', '数值'), ('select-1', '判断')], max_length=10, verbose_name='类型')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.column', verbose_name='列')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.row', verbose_name='行')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.record', verbose_name='表格')),
            ],
            options={
                'verbose_name': '作答标准',
                'verbose_name_plural': '作答标准',
            },
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.record', verbose_name='表格'),
        ),
        migrations.CreateModel(
            name='Choice_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('answer', models.CharField(max_length=10, verbose_name='答题')),
                ('belong_contestList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('belong_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.choice', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '选择题记录',
                'verbose_name_plural': '选择题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Choice_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.job', verbose_name='作业项目')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.choice', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '选择题目',
                'ordering': ['id'],
            },
        ),
    ]
