# Generated by Django 3.1.6 on 2021-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestlist',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
