# Generated by Django 3.1.6 on 2021-10-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20211007_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestlist',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='contestlist',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
