# Generated by Django 3.1.6 on 2021-10-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20211007_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='judge_answer',
            field=models.CharField(blank=True, choices=[(1, '正常'), (2, '维修'), (3, '更换'), (4, '调整')], max_length=10, null=True, verbose_name='判断正确值'),
        ),
    ]
