# Generated by Django 3.1.6 on 2021-10-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
        ('contest', '0005_auto_20211008_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerecord',
            name='judge_answer',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '维修'), (3, '更换'), (4, '调整')], null=True, verbose_name='判断答题值'),
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('submit', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('type', models.CharField(choices=[('表格', '表格'), ('理论', '理论')], default='理论', max_length=10, verbose_name='类型')),
                ('belong_contestList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestlist', verbose_name='竞赛')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='教师')),
            ],
            options={
                'verbose_name': '总成绩',
                'verbose_name_plural': '总成绩',
                'ordering': ['id'],
            },
        ),
    ]
