# Generated by Django 3.1.6 on 2021-10-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
        ('contest', '0006_auto_20211008_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobscore',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='裁判'),
        ),
        migrations.AlterField(
            model_name='jobtotal',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='裁判'),
        ),
        migrations.AlterField(
            model_name='merge',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='merge',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='裁判'),
        ),
    ]
