# Generated by Django 3.1.6 on 2021-10-02 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='考试名称')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('show', models.BooleanField(default=True, verbose_name='查看试卷')),
                ('disorder', models.BooleanField(default=True, verbose_name='题目乱序')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 14, 56, 8, 442021), verbose_name='开始时间')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 14, 56, 8, 442021), verbose_name='结束时间')),
                ('duration', models.IntegerField(default=120, verbose_name='时长')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('belong_te', models.ForeignKey(default='张超', on_delete=django.db.models.deletion.CASCADE, related_name='be_te', to='usermanage.teachers', verbose_name='教师')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gr_cl', to='usermanage.classes', verbose_name='考试班级')),
            ],
            options={
                'verbose_name': '考试名称',
                'verbose_name_plural': '考试管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='分数')),
                ('submit', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examinations', verbose_name='考试名称')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '学生成绩',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multiple_Choice_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examinations', verbose_name='考试名称')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.multiple_choice', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '多选题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examinations', verbose_name='考试名称')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.judge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '判断题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Choice_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bl_name', to='examination.examinations', verbose_name='考试名称')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bl_name', to='question.choice', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '选择题目',
                'ordering': ['id'],
            },
        ),
    ]
