# Generated by Django 3.1.6 on 2021-10-18 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0020_auto_20211018_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinations',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 22, 6, 52, 815882), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='examinations',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 22, 6, 52, 815882), verbose_name='开始时间'),
        ),
    ]
