# Generated by Django 3.1.6 on 2021-10-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('usermanage', '0004_auto_20211021_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='elecontest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='竞赛名称')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('type', models.IntegerField(choices=[(0, '实训'), (1, '竞赛')], default=0, verbose_name='类型')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('fault', models.TextField(blank=True, max_length=5000, null=True, verbose_name='故障设置')),
                ('file', models.FileField(blank=True, null=True, upload_to='electron/', verbose_name='工单')),
            ],
            options={
                'verbose_name': '电子竞赛',
                'verbose_name_plural': '电子竞赛',
            },
        ),
        migrations.CreateModel(
            name='station_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工位号')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
            },
        ),
        migrations.CreateModel(
            name='Results_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='分数')),
                ('submit', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('belong_ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_sta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electron.station_ele', verbose_name='工位号')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '学生成绩',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multiple_res_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('answer', models.CharField(max_length=10, verbose_name='答题')),
                ('belong_ele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.multiple_choice', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '多选题记录',
                'verbose_name_plural': '多选题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multiple_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.multiple_choice', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '多选题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge_res_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('answer', models.CharField(max_length=10, verbose_name='答题')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('belong_ele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.judge', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '判断题记录',
                'verbose_name_plural': '判断题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.judge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '判断题目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='electron/', verbose_name='工单')),
                ('belong_ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
            },
        ),
        migrations.CreateModel(
            name='Choice_res_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isscore', models.BooleanField(default=False, verbose_name='得分')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分值')),
                ('answer', models.CharField(max_length=10, verbose_name='答题')),
                ('belong_ele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.choice', verbose_name='题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.students', verbose_name='学生名字')),
            ],
            options={
                'verbose_name': '选择题记录',
                'verbose_name_plural': '选择题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Choice_ele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_ele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electron.elecontest', verbose_name='电子竞赛')),
                ('belong_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.choice', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '选择题目',
                'ordering': ['id'],
            },
        ),
    ]
