# Generated by Django 3.1.6 on 2021-10-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge_res_ele',
            name='remarks',
        ),
        migrations.AddField(
            model_name='elecontest',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
