# Generated by Django 3.1.6 on 2021-10-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('images', models.ImageField(default='course/timg.jpg', upload_to='course/', verbose_name='展示图')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, '自建'), (1, '官方')], default=0, null=True, verbose_name='类型')),
                ('belong_tid', models.ForeignKey(default='张超', on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('file', models.FileField(upload_to='file/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('MP4', 'MP4'), ('PDF', 'PDF')], default='PDF', max_length=10, verbose_name='文件类型')),
                ('type', models.IntegerField(blank=True, choices=[(0, '自建'), (1, '官方')], default=0, null=True, verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('belong_course', models.ForeignKey(default='汽车', on_delete=django.db.models.deletion.CASCADE, to='curriculum.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '资源管理',
                'ordering': ['id'],
            },
        ),
    ]
