# Generated by Django 3.1.6 on 2021-10-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='belong_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.teachers', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='belong_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.course', verbose_name='课程'),
        ),
    ]
